# base node image
FROM node:20-slim as base

# set for base and all layers that inherit from it
ENV NODE_ENV production

# Install openssl for Prisma and python
RUN apt-get update && apt-get install -y openssl procps python3 && rm -rf /var/lib/apt/lists/*

# Build the production image with minimal footprint
FROM base

WORKDIR /brockdev

ADD . .

RUN rm -rf /var/cache/apt/*

CMD ["npm", "run", "start"]