app = "brockdev"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "8080"
METRICS_PORT = "8081"

[metrics]
port = 8081  # Corrected the port number to match METRICS_PORT
path = "/metrics"

[deploy]
release_command = "bash ./scripts/migrate.sh"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.checks]]  # Changed from tcp_checks to checks
type = "tcp"
grace_period = "30s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.checks]]  # Added a healthcheck
type = "http"
interval = "10s"
grace_period = "30s"
method = "get"
path = "/healthcheck"
protocol = "http"
timeout = "30s"
tls_skip_verify = false
headers = {}
