export const borderDisplaySelectValues = [
  { id: "!border-none", name: "No Border" },
  { id: "border", name: "Display Border" },
  { id: "max-md:!border-none", name: "Hide Mobile" },
  { id: "md:!border-none", name: "Hide Desktop" },
];

export const borderSizeSelectValues = [
  { id: "border-[1px]", name: "1px" },
  { id: "border-[2px]", name: "2px" },
  { id: "border-[3px]", name: "3px" },
  { id: "border-[4px]", name: "4px" },
  { id: "border-[5px]", name: "5px" },
  { id: "border-[6px]", name: "6px" },
  { id: "border-[7px]", name: "7px" },
  { id: "border-[8px]", name: "8px" },
  { id: "border-[9px]", name: "9px" },
  { id: "border-[10px]", name: "10px" },
  { id: "border-[11px]", name: "11px" },
  { id: "border-[12px]", name: "12px" },
  { id: "border-[13px]", name: "13px" },
  { id: "border-[14px]", name: "14px" },
  { id: "border-[15px]", name: "15px" },
  { id: "border-[16px]", name: "16px" },
  { id: "border-[17px]", name: "17px" },
  { id: "border-[18px]", name: "18px" },
  { id: "border-[19px]", name: "19px" },
  { id: "border-[20px]", name: "20px" },
  { id: "border-[21px]", name: "21px" },
  { id: "border-[22px]", name: "22px" },
  { id: "border-[23px]", name: "23px" },
  { id: "border-[24px]", name: "24px" },
];

export const borderRadiusSelectValues = [
  { id: "rounded-sm", name: "Small" },
  { id: "rounded-md", name: "Medium" },
  { id: "rounded-lg", name: "Large" },
  { id: "rounded-xl", name: "X Large" },
  { id: "rounded-2xl", name: "2X Large" },
  { id: "rounded-3xl", name: "3X Large" },
  { id: "rounded-full", name: "Full" },
  { id: "mask mask-squircle !border-none", name: "Squircle" },
  { id: "mask mask-heart !border-none", name: "Heart" },
  { id: "rmask mask-hexagon !border-none", name: "Hexagon" },
  { id: "mask mask-hexagon-2 !border-none", name: "Hexagon 2" },
  { id: "mask mask-decagon !border-none", name: "Decagon" },
  { id: "mask mask-pentagon !border-none", name: "Pentagon" },
  { id: "mask mask-diamond !border-none", name: "Diamond" },
  { id: "mask mask-star !border-none", name: "Star" },
  { id: "mask mask-square !border-none", name: "Square" },
  { id: "mask mask-triangle !border-none", name: "Triangle" },
  { id: "mask mask-triangle-2 !border-none", name: "Triangle 2" },
  { id: "mask mask-triangle-3 !border-none", name: "Triangle 3" },
  { id: "mask mask-parallelogram !border-none", name: "Parallelogram" },
  { id: "mask mask-parallelogram-2 !border-none", name: "Parallelogram 2" },
  { id: "mask mask-parallelogram-3 !border-none", name: "Parallelogram 3" },
  { id: "mask mask-parallelogram-4 !border-none", name: "Parallelogram 4" },
];
