export const filterSelectValues = [
  { id: "filter invert", name: "Invert" },
  { id: "filter sepia", name: "Sepia" },
  { id: "filter grayscale", name: "Invert" },
  { id: "filter saturate-50", name: "Saturate Light" },
  { id: "filter saturate-100", name: "Saturate" },
  { id: "filter saturate-150", name: "Saturate Medium" },
  { id: "filter saturate-200", name: "Saturate Heavy" },
  { id: "filter brightness-50", name: "Brightness Light" },
  { id: "filter brightness-100", name: "Brightness" },
  { id: "filter brightness-150", name: "Brightness Medium" },
  { id: "filter brightness-200", name: "Brightness Heavy" },
  { id: "filter contrast-50", name: "Contrast Light" },
  { id: "filter contrast-100", name: "Contrast" },
  { id: "filter contrast-150", name: "Contrast Medium" },
  { id: "filter contrast-200", name: "Contrast Heavy" },
  { id: "filter blur-sm", name: "Blue Light" },
  { id: "filter blur", name: "Blur" },
  { id: "filter blur-md", name: "Blur Medium" },
  { id: "filter blur-lg", name: "Blur Heavy" },
];
