export const marginSelectValues = [
  { id: "max-md:!-mt-[13px] !-mt-6", name: "No Top" },
  { id: "max-md:-mt-[13px]", name: "No Top Mobile" },
  { id: "md:!-mt-6", name: "No Top Desktop" },

  { id: "max-md:!-mb-[13px] !-mb-6", name: "No Bottom" },
  { id: "max-md:-mb-[13px]", name: "No Bottom Mobile" },
  { id: "md:!-mb-6", name: "No Bottom Desktop" },

  { id: "max-md:!-my-[13px] !-my-6", name: "No Y" },
  { id: "max-md:-my-[13px]", name: "No Y Mobile" },
  { id: "md:!-my-6", name: "No Y Desktop" },

  { id: "max-md:!-mx-3 !-mx-6", name: "No X" },
  { id: "max-md:-mx-3", name: "No X Mobile" },
  { id: "md:!-mx-6", name: "No X Desktop" },
];

export const paddingSelectValues = [
  { id: "!pt-0", name: "No Top" },
  { id: "max-md:!pt-0", name: "No Top Mobile" },
  { id: "md:!pt-0", name: "No Top Desktop" },

  { id: "!pb-0", name: "No Bottom" },
  { id: "max-md:!pb-0", name: "No Bottom Mobile" },
  { id: "md:!pb-0", name: "No Bottom Desktop" },

  { id: "!py-0", name: "No Y" },
  { id: "max-md:!py-0", name: "No Y Mobile" },
  { id: "md:!py-0", name: "No Y Desktop" },

  { id: "!px-0", name: "No X" },
  { id: "max-md:!px-0", name: "No X Mobile" },
  { id: "md:!px-0", name: "No X Desktop" },
];

export const itemMarginTopSelectValues = [
  { id: "!-mt-1", name: "-1" },
  { id: "!-mt-1.5", name: "-1.5" },
  { id: "!-mt-2", name: "-2" },
  { id: "!-mt-2.5", name: "-2.5" },
  { id: "!-mt-3", name: "-3" },
  { id: "!-mt-3.5", name: "-3.5" },
  { id: "!-mt-4", name: "-4" },
  { id: "!-mt-5", name: "-5" },
  { id: "!-mt-6", name: "-6" },
  { id: "!-mt-7", name: "-7" },
  { id: "!-mt-8", name: "-8" },
  { id: "!-mt-9", name: "-9" },
  { id: "!-mt-10", name: "-10" },
  { id: "!mt-1", name: "1" },
  { id: "!mt-1.5", name: "1.5" },
  { id: "!mt-2", name: "2" },
  { id: "!mt-2.5", name: "2.5" },
  { id: "!mt-3", name: "3" },
  { id: "!mt-3.5", name: "3.5" },
  { id: "!mt-4", name: "4" },
  { id: "!mt-5", name: "5" },
  { id: "!mt-6", name: "6" },
  { id: "!mt-7", name: "7" },
  { id: "!mt-8", name: "8" },
  { id: "!mt-9", name: "9" },
  { id: "!mt-10", name: "10" },
];

export const mobileItemMarginTopSelectValues = [
  { id: "!max-md:-mt-1", name: "-1" },
  { id: "!max-md:-mt-1.5", name: "-1.5" },
  { id: "!max-md:-mt-2", name: "-2" },
  { id: "!max-md:-mt-2.5", name: "-2.5" },
  { id: "!max-md:-mt-3", name: "-3" },
  { id: "!max-md:-mt-3.5", name: "-3.5" },
  { id: "!max-md:-mt-4", name: "-4" },
  { id: "!max-md:-mt-5", name: "-5" },
  { id: "!max-md:-mt-6", name: "-6" },
  { id: "!max-md:-mt-7", name: "-7" },
  { id: "!max-md:-mt-8", name: "-8" },
  { id: "!max-md:-mt-9", name: "-9" },
  { id: "!max-md:-mt-10", name: "-10" },
  { id: "!max-md:mt-1", name: "1" },
  { id: "!max-md:mt-1.5", name: "1.5" },
  { id: "!max-md:mt-2", name: "2" },
  { id: "!max-md:mt-2.5", name: "2.5" },
  { id: "!max-md:mt-3", name: "3" },
  { id: "!max-md:mt-3.5", name: "3.5" },
  { id: "!max-md:mt-4", name: "4" },
  { id: "!max-md:mt-5", name: "5" },
  { id: "!max-md:mt-6", name: "6" },
  { id: "!max-md:mt-7", name: "7" },
  { id: "!max-md:mt-8", name: "8" },
  { id: "!max-md:mt-9", name: "9" },
  { id: "!max-md:mt-10", name: "10" },
];

export const itemMarginRightSelectValues = [
  { id: "!-mr-1", name: "-1" },
  { id: "!-mr-1.5", name: "-1.5" },
  { id: "!-mr-2", name: "-2" },
  { id: "!-mr-2.5", name: "-2.5" },
  { id: "!-mr-3", name: "-3" },
  { id: "!-mr-3.5", name: "-3.5" },
  { id: "!-mr-4", name: "-4" },
  { id: "!-mr-5", name: "-5" },
  { id: "!-mr-6", name: "-6" },
  { id: "!-mr-7", name: "-7" },
  { id: "!-mr-8", name: "-8" },
  { id: "!-mr-9", name: "-9" },
  { id: "!-mr-10", name: "-10" },
  { id: "!mr-1", name: "1" },
  { id: "!mr-1.5", name: "1.5" },
  { id: "!mr-2", name: "2" },
  { id: "!mr-2.5", name: "2.5" },
  { id: "!mr-3", name: "3" },
  { id: "!mr-3.5", name: "3.5" },
  { id: "!mr-4", name: "4" },
  { id: "!mr-5", name: "5" },
  { id: "!mr-6", name: "6" },
  { id: "!mr-7", name: "7" },
  { id: "!mr-8", name: "8" },
  { id: "!mr-9", name: "9" },
  { id: "!mr-10", name: "10" },
];

export const mobileItemMarginRightSelectValues = [
  { id: "!max-md:-mr-1", name: "-1" },
  { id: "!max-md:-mr-1.5", name: "-1.5" },
  { id: "!max-md:-mr-2", name: "-2" },
  { id: "!max-md:-mr-2.5", name: "-2.5" },
  { id: "!max-md:-mr-3", name: "-3" },
  { id: "!max-md:-mr-3.5", name: "-3.5" },
  { id: "!max-md:-mr-4", name: "-4" },
  { id: "!max-md:-mr-5", name: "-5" },
  { id: "!max-md:-mr-6", name: "-6" },
  { id: "!max-md:-mr-7", name: "-7" },
  { id: "!max-md:-mr-8", name: "-8" },
  { id: "!max-md:-mr-9", name: "-9" },
  { id: "!max-md:-mr-10", name: "-10" },
  { id: "!max-md:mr-1", name: "1" },
  { id: "!max-md:mr-1.5", name: "1.5" },
  { id: "!max-md:mr-2", name: "2" },
  { id: "!max-md:mr-2.5", name: "2.5" },
  { id: "!max-md:mr-3", name: "3" },
  { id: "!max-md:mr-3.5", name: "3.5" },
  { id: "!max-md:mr-4", name: "4" },
  { id: "!max-md:mr-5", name: "5" },
  { id: "!max-md:mr-6", name: "6" },
  { id: "!max-md:mr-7", name: "7" },
  { id: "!max-md:mr-8", name: "8" },
  { id: "!max-md:mr-9", name: "9" },
  { id: "!max-md:mr-10", name: "10" },
];

export const itemMarginBottomSelectValues = [
  { id: "!-mb-1", name: "-1" },
  { id: "!-mb-1.5", name: "-1.5" },
  { id: "!-mb-2", name: "-2" },
  { id: "!-mb-2.5", name: "-2.5" },
  { id: "!-mb-3", name: "-3" },
  { id: "!-mb-3.5", name: "-3.5" },
  { id: "!-mb-4", name: "-4" },
  { id: "!-mb-5", name: "-5" },
  { id: "!-mb-6", name: "-6" },
  { id: "!-mb-7", name: "-7" },
  { id: "!-mb-8", name: "-8" },
  { id: "!-mb-9", name: "-9" },
  { id: "!-mb-10", name: "-10" },
  { id: "!mb-1", name: "1" },
  { id: "!mb-1.5", name: "1.5" },
  { id: "!mb-2", name: "2" },
  { id: "!mb-2.5", name: "2.5" },
  { id: "!mb-3", name: "3" },
  { id: "!mb-3.5", name: "3.5" },
  { id: "!mb-4", name: "4" },
  { id: "!mb-5", name: "5" },
  { id: "!mb-6", name: "6" },
  { id: "!mb-7", name: "7" },
  { id: "!mb-8", name: "8" },
  { id: "!mb-9", name: "9" },
  { id: "!mb-10", name: "10" },
];

export const mobileItemMarginBottomSelectValues = [
  { id: "!max-md:-mb-1", name: "-1" },
  { id: "!max-md:-mb-1.5", name: "-1.5" },
  { id: "!max-md:-mb-2", name: "-2" },
  { id: "!max-md:-mb-2.5", name: "-2.5" },
  { id: "!max-md:-mb-3", name: "-3" },
  { id: "!max-md:-mb-3.5", name: "-3.5" },
  { id: "!max-md:-mb-4", name: "-4" },
  { id: "!max-md:-mb-5", name: "-5" },
  { id: "!max-md:-mb-6", name: "-6" },
  { id: "!max-md:-mb-7", name: "-7" },
  { id: "!max-md:-mb-8", name: "-8" },
  { id: "!max-md:-mb-9", name: "-9" },
  { id: "!max-md:-mb-10", name: "-10" },
  { id: "!max-md:mb-1", name: "1" },
  { id: "!max-md:mb-1.5", name: "1.5" },
  { id: "!max-md:mb-2", name: "2" },
  { id: "!max-md:mb-2.5", name: "2.5" },
  { id: "!max-md:mb-3", name: "3" },
  { id: "!max-md:mb-3.5", name: "3.5" },
  { id: "!max-md:mb-4", name: "4" },
  { id: "!max-md:mb-5", name: "5" },
  { id: "!max-md:mb-6", name: "6" },
  { id: "!max-md:mb-7", name: "7" },
  { id: "!max-md:mb-8", name: "8" },
  { id: "!max-md:mb-9", name: "9" },
  { id: "!max-md:mb-10", name: "10" },
];

export const itemMarginLeftSelectValues = [
  { id: "!-ml-1", name: "-1" },
  { id: "!-ml-1.5", name: "-1.5" },
  { id: "!-ml-2", name: "-2" },
  { id: "!-ml-2.5", name: "-2.5" },
  { id: "!-ml-3", name: "-3" },
  { id: "!-ml-3.5", name: "-3.5" },
  { id: "!-ml-4", name: "-4" },
  { id: "!-ml-5", name: "-5" },
  { id: "!-ml-6", name: "-6" },
  { id: "!-ml-7", name: "-7" },
  { id: "!-ml-8", name: "-8" },
  { id: "!-ml-9", name: "-9" },
  { id: "!-ml-10", name: "-10" },
  { id: "!ml-1", name: "1" },
  { id: "!ml-1.5", name: "1.5" },
  { id: "!ml-2", name: "2" },
  { id: "!ml-2.5", name: "2.5" },
  { id: "!ml-3", name: "3" },
  { id: "!ml-3.5", name: "3.5" },
  { id: "!ml-4", name: "4" },
  { id: "!ml-5", name: "5" },
  { id: "!ml-6", name: "6" },
  { id: "!ml-7", name: "7" },
  { id: "!ml-8", name: "8" },
  { id: "!ml-9", name: "9" },
  { id: "!ml-10", name: "10" },
];

export const mobileItemMarginLeftSelectValues = [
  { id: "!max-md:-ml-1", name: "-1" },
  { id: "!max-md:-ml-1.5", name: "-1.5" },
  { id: "!max-md:-ml-2", name: "-2" },
  { id: "!max-md:-ml-2.5", name: "-2.5" },
  { id: "!max-md:-ml-3", name: "-3" },
  { id: "!max-md:-ml-3.5", name: "-3.5" },
  { id: "!max-md:-ml-4", name: "-4" },
  { id: "!max-md:-ml-5", name: "-5" },
  { id: "!max-md:-ml-6", name: "-6" },
  { id: "!max-md:-ml-7", name: "-7" },
  { id: "!max-md:-ml-8", name: "-8" },
  { id: "!max-md:-ml-9", name: "-9" },
  { id: "!max-md:-ml-10", name: "-10" },
  { id: "!max-md:ml-1", name: "1" },
  { id: "!max-md:ml-1.5", name: "1.5" },
  { id: "!max-md:ml-2", name: "2" },
  { id: "!max-md:ml-2.5", name: "2.5" },
  { id: "!max-md:ml-3", name: "3" },
  { id: "!max-md:ml-3.5", name: "3.5" },
  { id: "!max-md:ml-4", name: "4" },
  { id: "!max-md:ml-5", name: "5" },
  { id: "!max-md:ml-6", name: "6" },
  { id: "!max-md:ml-7", name: "7" },
  { id: "!max-md:ml-8", name: "8" },
  { id: "!max-md:ml-9", name: "9" },
  { id: "!max-md:ml-10", name: "10" },
];

export const itemPaddingTopSelectValues = [
  { id: "!-pt-1", name: "-1" },
  { id: "!-pt-1.5", name: "-1.5" },
  { id: "!-pt-2", name: "-2" },
  { id: "!-pt-2.5", name: "-2.5" },
  { id: "!-pt-3", name: "-3" },
  { id: "!-pt-3.5", name: "-3.5" },
  { id: "!-pt-4", name: "-4" },
  { id: "!-pt-5", name: "-5" },
  { id: "!-pt-6", name: "-6" },
  { id: "!-pt-7", name: "-7" },
  { id: "!-pt-8", name: "-8" },
  { id: "!-pt-9", name: "-9" },
  { id: "!-pt-10", name: "-10" },
  { id: "!pt-1", name: "1" },
  { id: "!pt-1.5", name: "1.5" },
  { id: "!pt-2", name: "2" },
  { id: "!pt-2.5", name: "2.5" },
  { id: "!pt-3", name: "3" },
  { id: "!pt-3.5", name: "3.5" },
  { id: "!pt-4", name: "4" },
  { id: "!pt-5", name: "5" },
  { id: "!pt-6", name: "6" },
  { id: "!pt-7", name: "7" },
  { id: "!pt-8", name: "8" },
  { id: "!pt-9", name: "9" },
  { id: "!pt-10", name: "10" },
];

export const mobileItemPaddingTopSelectValues = [
  { id: "max-md:!-pt-1", name: "-1" },
  { id: "max-md:!-pt-1.5", name: "-1.5" },
  { id: "max-md:!-pt-2", name: "-2" },
  { id: "max-md:!-pt-2.5", name: "-2.5" },
  { id: "max-md:!-pt-3", name: "-3" },
  { id: "max-md:!-pt-3.5", name: "-3.5" },
  { id: "max-md:!-pt-4", name: "-4" },
  { id: "max-md:!-pt-5", name: "-5" },
  { id: "max-md:!-pt-6", name: "-6" },
  { id: "max-md:!-pt-7", name: "-7" },
  { id: "max-md:!-pt-8", name: "-8" },
  { id: "max-md:!-pt-9", name: "-9" },
  { id: "max-md:!-pt-10", name: "-10" },
  { id: "max-md:!pt-1", name: "1" },
  { id: "max-md:!pt-1.5", name: "1.5" },
  { id: "max-md:!pt-2", name: "2" },
  { id: "max-md:!pt-2.5", name: "2.5" },
  { id: "max-md:!pt-3", name: "3" },
  { id: "max-md:!pt-3.5", name: "3.5" },
  { id: "max-md:!pt-4", name: "4" },
  { id: "max-md:!pt-5", name: "5" },
  { id: "max-md:!pt-6", name: "6" },
  { id: "max-md:!pt-7", name: "7" },
  { id: "max-md:!pt-8", name: "8" },
  { id: "max-md:!pt-9", name: "9" },
  { id: "max-md:!pt-10", name: "10" },
];

export const itemPaddingRightSelectValues = [
  { id: "!-pr-1", name: "-1" },
  { id: "!-pr-1.5", name: "-1.5" },
  { id: "!-pr-2", name: "-2" },
  { id: "!-pr-2.5", name: "-2.5" },
  { id: "!-pr-3", name: "-3" },
  { id: "!-pr-3.5", name: "-3.5" },
  { id: "!-pr-4", name: "-4" },
  { id: "!-pr-5", name: "-5" },
  { id: "!-pr-6", name: "-6" },
  { id: "!-pr-7", name: "-7" },
  { id: "!-pr-8", name: "-8" },
  { id: "!-pr-9", name: "-9" },
  { id: "!-pr-10", name: "-10" },
  { id: "!pr-1", name: "1" },
  { id: "!pr-1.5", name: "1.5" },
  { id: "!pr-2", name: "2" },
  { id: "!pr-2.5", name: "2.5" },
  { id: "!pr-3", name: "3" },
  { id: "!pr-3.5", name: "3.5" },
  { id: "!pr-4", name: "4" },
  { id: "!pr-5", name: "5" },
  { id: "!pr-6", name: "6" },
  { id: "!pr-7", name: "7" },
  { id: "!pr-8", name: "8" },
  { id: "!pr-9", name: "9" },
  { id: "!pr-10", name: "10" },
];

export const mobileItemPaddingRightSelectValues = [
  { id: "max-md:!-pr-1", name: "-1" },
  { id: "max-md:!-pr-1.5", name: "-1.5" },
  { id: "max-md:!-pr-2", name: "-2" },
  { id: "max-md:!-pr-2.5", name: "-2.5" },
  { id: "max-md:!-pr-3", name: "-3" },
  { id: "max-md:!-pr-3.5", name: "-3.5" },
  { id: "max-md:!-pr-4", name: "-4" },
  { id: "max-md:!-pr-5", name: "-5" },
  { id: "max-md:!-pr-6", name: "-6" },
  { id: "max-md:!-pr-7", name: "-7" },
  { id: "max-md:!-pr-8", name: "-8" },
  { id: "max-md:!-pr-9", name: "-9" },
  { id: "max-md:!-pr-10", name: "-10" },
  { id: "max-md:!pr-1", name: "1" },
  { id: "max-md:!pr-1.5", name: "1.5" },
  { id: "max-md:!pr-2", name: "2" },
  { id: "max-md:!pr-2.5", name: "2.5" },
  { id: "max-md:!pr-3", name: "3" },
  { id: "max-md:!pr-3.5", name: "3.5" },
  { id: "max-md:!pr-4", name: "4" },
  { id: "max-md:!pr-5", name: "5" },
  { id: "max-md:!pr-6", name: "6" },
  { id: "max-md:!pr-7", name: "7" },
  { id: "max-md:!pr-8", name: "8" },
  { id: "max-md:!pr-9", name: "9" },
  { id: "max-md:!pr-10", name: "10" },
];

export const itemPaddingBottomSelectValues = [
  { id: "!-pb-1", name: "-1" },
  { id: "!-pb-1.5", name: "-1.5" },
  { id: "!-pb-2", name: "-2" },
  { id: "!-pb-2.5", name: "-2.5" },
  { id: "!-pb-3", name: "-3" },
  { id: "!-pb-3.5", name: "-3.5" },
  { id: "!-pb-4", name: "-4" },
  { id: "!-pb-5", name: "-5" },
  { id: "!-pb-6", name: "-6" },
  { id: "!-pb-7", name: "-7" },
  { id: "!-pb-8", name: "-8" },
  { id: "!-pb-9", name: "-9" },
  { id: "!-pb-10", name: "-10" },
  { id: "!pb-1", name: "1" },
  { id: "!pb-1.5", name: "1.5" },
  { id: "!pb-2", name: "2" },
  { id: "!pb-2.5", name: "2.5" },
  { id: "!pb-3", name: "3" },
  { id: "!pb-3.5", name: "3.5" },
  { id: "!pb-4", name: "4" },
  { id: "!pb-5", name: "5" },
  { id: "!pb-6", name: "6" },
  { id: "!pb-7", name: "7" },
  { id: "!pb-8", name: "8" },
  { id: "!pb-9", name: "9" },
  { id: "!pb-10", name: "10" },
];

export const mobileItemPaddingBottomSelectValues = [
  { id: "max-md:!-pb-1", name: "-1" },
  { id: "max-md:!-pb-1.5", name: "-1.5" },
  { id: "max-md:!-pb-2", name: "-2" },
  { id: "max-md:!-pb-2.5", name: "-2.5" },
  { id: "max-md:!-pb-3", name: "-3" },
  { id: "max-md:!-pb-3.5", name: "-3.5" },
  { id: "max-md:!-pb-4", name: "-4" },
  { id: "max-md:!-pb-5", name: "-5" },
  { id: "max-md:!-pb-6", name: "-6" },
  { id: "max-md:!-pb-7", name: "-7" },
  { id: "max-md:!-pb-8", name: "-8" },
  { id: "max-md:!-pb-9", name: "-9" },
  { id: "max-md:!-pb-10", name: "-10" },
  { id: "max-md:!pb-1", name: "1" },
  { id: "max-md:!pb-1.5", name: "1.5" },
  { id: "max-md:!pb-2", name: "2" },
  { id: "max-md:!pb-2.5", name: "2.5" },
  { id: "max-md:!pb-3", name: "3" },
  { id: "max-md:!pb-3.5", name: "3.5" },
  { id: "max-md:!pb-4", name: "4" },
  { id: "max-md:!pb-5", name: "5" },
  { id: "max-md:!pb-6", name: "6" },
  { id: "max-md:!pb-7", name: "7" },
  { id: "max-md:!pb-8", name: "8" },
  { id: "max-md:!pb-9", name: "9" },
  { id: "max-md:!pb-10", name: "10" },
];

export const itemPaddingLeftSelectValues = [
  { id: "!-pl-1", name: "-1" },
  { id: "!-pl-1.5", name: "-1.5" },
  { id: "!-pl-2", name: "-2" },
  { id: "!-pl-2.5", name: "-2.5" },
  { id: "!-pl-3", name: "-3" },
  { id: "!-pl-3.5", name: "-3.5" },
  { id: "!-pl-4", name: "-4" },
  { id: "!-pl-5", name: "-5" },
  { id: "!-pl-6", name: "-6" },
  { id: "!-pl-7", name: "-7" },
  { id: "!-pl-8", name: "-8" },
  { id: "!-pl-9", name: "-9" },
  { id: "!-pl-10", name: "-10" },
  { id: "!pl-1", name: "1" },
  { id: "!pl-1.5", name: "1.5" },
  { id: "!pl-2", name: "2" },
  { id: "!pl-2.5", name: "2.5" },
  { id: "!pl-3", name: "3" },
  { id: "!pl-3.5", name: "3.5" },
  { id: "!pl-4", name: "4" },
  { id: "!pl-5", name: "5" },
  { id: "!pl-6", name: "6" },
  { id: "!pl-7", name: "7" },
  { id: "!pl-8", name: "8" },
  { id: "!pl-9", name: "9" },
  { id: "!pl-10", name: "10" },
];

export const mobileItemPaddingLeftSelectValues = [
  { id: "max-md:!-pl-1", name: "-1" },
  { id: "max-md:!-pl-1.5", name: "-1.5" },
  { id: "max-md:!-pl-2", name: "-2" },
  { id: "max-md:!-pl-2.5", name: "-2.5" },
  { id: "max-md:!-pl-3", name: "-3" },
  { id: "max-md:!-pl-3.5", name: "-3.5" },
  { id: "max-md:!-pl-4", name: "-4" },
  { id: "max-md:!-pl-5", name: "-5" },
  { id: "max-md:!-pl-6", name: "-6" },
  { id: "max-md:!-pl-7", name: "-7" },
  { id: "max-md:!-pl-8", name: "-8" },
  { id: "max-md:!-pl-9", name: "-9" },
  { id: "max-md:!-pl-10", name: "-10" },
  { id: "max-md:!pl-1", name: "1" },
  { id: "max-md:!pl-1.5", name: "1.5" },
  { id: "max-md:!pl-2", name: "2" },
  { id: "max-md:!pl-2.5", name: "2.5" },
  { id: "max-md:!pl-3", name: "3" },
  { id: "max-md:!pl-3.5", name: "3.5" },
  { id: "max-md:!pl-4", name: "4" },
  { id: "max-md:!pl-5", name: "5" },
  { id: "max-md:!pl-6", name: "6" },
  { id: "max-md:!pl-7", name: "7" },
  { id: "max-md:!pl-8", name: "8" },
  { id: "max-md:!pl-9", name: "9" },
  { id: "max-md:!pl-10", name: "10" },
];
